#!/usr/bin/env python3
"""Build a lightweight text index of the textbook PDFs.

Run ONCE:  python scripts/index_textbooks.py

Why this exists: the PDFs in the parent folder total ~90 MB. Feeding them
into a Claude Code context would burn an enormous amount of usage for very
little benefit. Instead this extracts each book's table of contents into a
small markdown file, so that a lesson's "Textbook cross-reference" note can
point the tutor at the right chapter without any model ever reading the PDF.

Requires poppler-utils (pdftotext) on PATH.
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOOKS = ROOT.parent                       # the SAT Math folder holding the PDFs
OUT = ROOT / "curriculum" / "reference-index.md"

TOC_HINT = re.compile(r"(chapter|unit|lesson|part|section)\s+\d+", re.I)


def toc_for(pdf: Path) -> list[str]:
    """Pull plausible table-of-contents lines from the first 25 pages."""
    try:
        txt = subprocess.run(
            ["pdftotext", "-f", "1", "-l", "25", "-layout", str(pdf), "-"],
            capture_output=True, text=True, timeout=120, check=True,
        ).stdout
    except Exception as e:                      # noqa: BLE001
        return [f"_could not read: {e}_"]

    seen, out = set(), []
    for raw in txt.splitlines():
        line = raw.strip()
        if not (8 < len(line) < 90):
            continue
        if not TOC_HINT.search(line):
            continue
        line = re.sub(r"\.{3,}\s*\d+\s*$", "", line).strip()
        key = line.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(line)
    return out[:60]


def main() -> int:
    pdfs = sorted(BOOKS.glob("*.pdf"))
    if not pdfs:
        print(f"No PDFs found in {BOOKS}", file=sys.stderr)
        return 1

    lines = [
        "# Textbook reference index",
        "",
        "Auto-generated by `scripts/index_textbooks.py`. Do not edit by hand.",
        "",
        "These books are the **tutor's** reference for extra practice and alternative",
        "explanations. They are copyrighted and are neither committed to this repo nor",
        "read by any agent. Use this index to find a chapter, then open the PDF yourself.",
        "",
    ]
    for pdf in pdfs:
        lines += [f"## {pdf.stem[:90]}", "", f"`{pdf.name}`  -  {pdf.stat().st_size // 1_000_000} MB", ""]
        toc = toc_for(pdf)
        lines += [f"- {t}" for t in toc] if toc else ["_no table of contents detected_"]
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Indexed {len(pdfs)} books -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
